version: 1.1.0.{build}

configuration:
- Release

environment:

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: 15 2017
    VS_PLATFORM: win32


before_build:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg integrate install
  - vcpkg install brynet --head
  - vcpkg install protobuf:x86-windows
  - vcpkg install protobuf:x64-windows
  - SET PATH=C:\Tools\vcpkg\installed\x86-windows\tools\protobuf;%PATH%
  - SET PATH=C:\Tools\vcpkg\installed\x86-windows\lib;%PATH%
  - SET PATH=C:\Tools\vcpkg\installed\x64-windows\lib;%PATH%
  - SET APPVEYOR_CI=1
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - cd %APPVEYOR_BUILD_FOLDER%/src
  - protoc -I. -IC:\Tools\vcpkg\installed\x86-windows\include --cpp_out=. ./gayrpc/core/gayrpc_meta.proto ./gayrpc/core/gayrpc_option.proto
  - cd %APPVEYOR_BUILD_FOLDER%/examples/echo/pb
  - protoc -I. -I../../../src -IC:\Tools\vcpkg\installed\x86-windows\include --cpp_out=. echo_service.proto
  - cd %APPVEYOR_BUILD_FOLDER%/examples/benchmark/pb
  - protoc -I. -I../../../src -IC:\Tools\vcpkg\installed\x86-windows\include --cpp_out=. benchmark_service.proto
  - cd %APPVEYOR_BUILD_FOLDER%/tests/pb
  - protoc -I. -I../../src -IC:\Tools\vcpkg\installed\x86-windows\include --cpp_out=. echo_service.proto
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo Running cmake...
  - cmake -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake . -G "Visual Studio %VS_VERSION%" -DVCPKG_OVERLAY_PORTS="%APPVEYOR_BUILD_FOLDER%/vcpkg/overlay/folly"

build:
  project: gayrpc.sln
  parallel: true
  verbosity: minimal

test_script:
    - cd tests
    - ctest -V -C %CONFIGURATION%